name: Git Checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd shop_backend && pip install -r requirements.txt
      - name: Black check
        run: black --check shop_backend
      - name: Flake check
        run: cd shop_backend && flake8 --count
